name: Playwright Tests  # Name of the workflow

on:
  push:
    branches: [main, develop]  # Runs on every push to main or develop
  pull_request:
    branches: [main, develop]  # Runs on PRs targeting these branches
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on a Linux machine

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Gets the latest code

      - name: Debug - Check Files in Runner
        run: |
          echo "Listing files in working directory..."
          ls -la
          echo "Checking for yarn.lock file..."
          if [ -f yarn.lock ]; then
            echo "✅ yarn.lock FOUND!"
          else
            echo "❌ ERROR: yarn.lock NOT FOUND!"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'  # Caches dependencies for faster runs

      - name: Install Dependencies
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            echo "❌ ERROR: yarn.lock is missing. Stopping build."
            exit 1
          fi

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Test Results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/